# Generated by Django 4.1 on 2022-10-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_task_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default='07.10.2022 23:06:24'),
        ),
    ]
