# Generated by Django 4.1 on 2022-09-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_rename_mywatchlist_mywatchlists'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyWatchLists',
            new_name='MyWatchList',
        ),
    ]
